export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

// regestration
export const USER_REGESTER_REQUEST = "USER_REGESTER_REQUEST"
export const USER_REGESTER_SUCCESS = "USER_REGESTER_SUCCESS"
export const USER_REGESTER_FAIL = "USER_REGESTER_FAIL"